### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by john9000100**
Split up code and stls by sections: base, torso, arm, gripper

### CODE REVIEW

**Comment by TheDash** [comment]
I can't automatically merge this (sorry for the delay here). Does the simulator still work/everything compile after these changes?

**Comment by john9000100** [comment]
Yes, everything still works. For merging, I thought the only conflict was the gitignore?

**Comment by TheDash** [comment]
I think you have access to push/pull to this repo (or you should). I've looked through the code and give my +1. Feel free to manually merging it using the Git suggested commands.

**Comment by TheDash** [comment]
+1. Merged #1

**Pull request merged**
