### PR TITLE
Adding details

### PR DESCRIPTION
**Pull request by john9000100**
Added more detailed stls and mimic tag for elbow joint

### CODE REVIEW

**Comment by TheDash** [comment]
Did you test this with teleop? Is the robot still stable after these changes?

**Comment by john9000100** [comment]
i'll check

**Comment by TheDash** [comment]
Since we don't have continuous integration we need to make sure the build is always working by manually checking.

**Comment by john9000100** [comment]
Why does the indigo-devel robot move around by itself after using roslaunch talos_gazebo talos.launch?

**Comment by TheDash** [comment]
It shouldnt, if its just a bit of sliding... it needs more friction.

**Comment by TheDash** [comment]
The physics values have always been wrong

**Comment by john9000100** [comment]
oh haha it was wandering around like someone was controlling it. For physics, I think Shams is getting the inertial values. I'll try to fix the friction. Any tips? Would we need to measure these physically?

**Comment by TheDash** [comment]
If we want a proper physics simulation then yeah

**Comment by john9000100** [comment]
kay!

**Comment by john9000100** [comment]
still seems stable

**Comment by TheDash** [comment]
FYI the talos_moveit_config package needs to be updated whenever something is changed in the description model. 

You'll need to update the config/*.srdf  file to fix the collisions mentioned in this picture so that they have proper colilsoin rules and then make a PR.

To bring up this yourself, run the talos.launch in the simulator and then from the moveit_config packages

you'll run

roslaunch talos_moveit_config talos_moveit_planning_execution.launch sim:=true
roslaunch talos_moveit_config moveit_rviz.launch config:=true

And then look inside the status tab of the manipulation window.

It should be clear from there. But please fix it, otherwise it's blocking the development of our grasping/sensor integration with moveit.

**Comment by john9000100** [comment]
ah sorry, will work on this when I get home tonigth

**Comment by john9000100** [comment]
What's a PR?

**Comment by TheDash** [comment]
pull request

**Comment by john9000100** [comment]
Where's the picture your referring to?

**Comment by john9000100** [comment]
hmm gazebo consistently freezes my computer; even using the "-r" option, i can't get it to load without the GUI

**Comment by TheDash** [comment]
Oh sorry i forgot the pic. ill take one l8r. gazebo sucks in general ol

**Comment by john9000100** [comment]
lol

**Comment by john9000100** [comment]
still working on this..sry

**Pull request merged**
